import { asset } from "../lib/asset";
import type { Lesson } from "../lib/schema";

export const bai1: Lesson = {
  id: "bai-1",
  number: 1,
  slug: "menh-de",
  title: "Mệnh đề",
  shortTitle: "Mệnh đề",
  chapter: "Chương I",
  periods: 3,
  blurb: "Logic · phủ định · kéo theo · ∀ ∃",
  theme: {
    id: "logic",
    accentFrom: "#3b82f6",
    accentTo: "#2563eb",
    mapBoardClass: "",
    nodeClass: "",
    xpLabel: "XP",
    mapName: "Challenge Map",
    sectionPrefix: "Mức",
    chestClosed: "📦",
    chestOpen: "🎁",
    successText: "Chính xác!",
    failText: "Chưa đúng.",
    lockedToast: "Hãy mở mốc trước đã!",
    resetLabel: "Chơi lại từ đầu",
    resetConfirm: "Xóa tiến độ Challenge Map Bài 1?",
    brandMark: "book",
  },
  progressKey: "toan-thpt-map-menhde-v1",
  levelLabels: { 1: "Nhận biết", 2: "Thông hiểu", 3: "Vận dụng", 4: "Vận dụng cao" },
  xpByLevel: { 1: 10, 2: 15, 3: 20, 4: 30 },
  sidebarFoot: "← → chuyển slide · làm đúng trên map để mở mốc tiếp theo.",
  slides: [
    {
      type: "hero",
      title: "Mở đầu",
      eyebrow: "Toán 10 · Chương I · 3 tiết",
      heading: "Bài 1. Mệnh đề",
      body: "Hôm nay ta bước vào chương đầu tiên: <strong>Mệnh đề và tập hợp</strong>. Cùng quan sát – tranh luận – chốt kiến thức!",
      image: asset("images/slide-debate.jpg"),
      imageAlt: "Học sinh thảo luận",
    },
    {
      type: "quiz",
      title: "Tình huống mở đầu",
      banner: "Hoạt động mở đầu · Tương tác",
      bannerTone: "orange",
      heading: "Ai nói đúng về số con vật?",
      prompt: "Chọn một ý kiến, rồi bấm <strong>Kiểm tra</strong>.",
      image: asset("images/sgk-animals.jpg"),
      imageAlt: "Hình con vật trong SGK",
      quiz: {
        kind: "single",
        variant: "vs",
        correct: 1,
        explain:
          "Trong hình có voi, khỉ, ngựa, chó, mèo, chuột — <strong>6</strong> con vật. Khoa đúng, An sai. Câu hỏi “Có bao nhiêu…?” không phải mệnh đề.",
        options: [
          { html: "<strong>An nói</strong><p>“Có <b>5</b> con vật xuất hiện trong hình vẽ.”</p>" },
          { html: "<strong>Khoa nói</strong><p>“Có <b>6</b> con vật xuất hiện trong hình vẽ.”</p>" },
        ],
      },
    },
    {
      type: "content",
      title: "Nội dung bài học",
      banner: "Lộ trình 5 phần",
      bannerTone: "blue",
      heading: "Nội dung bài học hôm nay",
      image: asset("images/slide-overview.jpg"),
      parts: [
        { n: "1", title: "Mệnh đề", text: "Mệnh đề &amp; chứa biến", color: "#2563eb" },
        { n: "2", title: "Phủ định", text: "Lập \\(\\overline{P}\\)", color: "#f97316" },
        { n: "3", title: "Kéo theo · Đảo", text: "\\(P \\Rightarrow Q\\)", color: "#14b8a6" },
        { n: "4", title: "Tương đương", text: "\\(P \\Leftrightarrow Q\\)", color: "#8b5cf6" },
        { n: "5", title: "Lượng từ", text: "\\(\\forall\\) và \\(\\exists\\)", color: "#e11d48" },
      ],
    },
    {
      type: "quiz",
      title: "Nhận biết mệnh đề",
      banner: "Phần 1 · Tương tác",
      bannerTone: "blue",
      heading: "Chọn tất cả câu <em>là mệnh đề</em>",
      prompt: "Có thể chọn nhiều đáp án, rồi bấm Kiểm tra.",
      quiz: {
        kind: "multi",
        correct: [0, 1],
        explain: "A và B là mệnh đề (khẳng định đúng/sai). C là câu hỏi, D là câu cảm thán — không phải mệnh đề.",
        options: [
          { html: "Phương trình \\(3x^2 - 5x + 2 = 0\\) có nghiệm nguyên." },
          { html: "\\(5 &lt; 7 - 3\\)." },
          { html: "Có bao nhiêu dấu hiệu nhận biết hai tam giác đồng dạng?" },
          { html: "Đấy là cách xử lý khôn ngoan!" },
        ],
      },
    },
    {
      type: "content",
      title: "Định nghĩa mệnh đề",
      banner: "Phần 1 · Chốt kiến thức",
      bannerTone: "blue",
      heading: "Mệnh đề là gì?",
      definition: "<strong>Mệnh đề</strong> là một câu khẳng định đúng hoặc sai.",
      bullets: [
        "Mỗi mệnh đề <em>hoặc đúng, hoặc sai</em> — không vừa đúng vừa sai.",
        "Câu hỏi, câu cảm thán, câu mệnh lệnh <strong>không</strong> là mệnh đề.",
      ],
      tags: ["“13 là số nguyên tố” → đúng", "“Bạn làm bài chưa?” → không phải"],
    },
    {
      type: "quiz",
      title: "Tranh luận đúng/sai",
      banner: "Tình huống · Tương tác",
      bannerTone: "orange",
      heading: "Ai đúng trong cuộc tranh luận?",
      image: asset("images/sgk-debate-prime.jpg"),
      quiz: {
        kind: "single",
        variant: "vs",
        correct: 0,
        explain: "Cả hai câu đều là mệnh đề. \\(2003\\) là số nguyên tố → Bình đúng, An sai.",
        options: [
          { html: "<strong>Bình</strong><p>“\\(2003\\) là số nguyên tố.”</p>" },
          { html: "<strong>An</strong><p>“\\(2003\\) không phải là số nguyên tố.”</p>" },
        ],
      },
    },
    {
      type: "content",
      title: "Mệnh đề chứa biến",
      banner: "Phần 1",
      bannerTone: "blue",
      heading: "Mệnh đề chứa biến",
      image: asset("images/slide-animals.jpg"),
      definition: "Xét câu: “\\(n\\) chia hết cho \\(2\\)” với \\(n\\) là số tự nhiên.",
      bullets: [
        "Chưa gán \\(n\\) → chưa xác định đúng/sai.",
        "\\(n = 5\\) → “5 chia hết cho 2” → sai",
        "\\(n = 10\\) → “10 chia hết cho 2” → đúng",
      ],
      callout: "Câu khẳng định chứa biến, đúng/sai phụ thuộc giá trị biến → <strong>mệnh đề chứa biến</strong>.",
    },
    {
      type: "quiz",
      title: "Biển báo · Phủ định",
      banner: "Phần 2 · Tương tác",
      bannerTone: "orange",
      heading: "An phủ định Khoa thế nào?",
      prompt: "Khoa: “Đây là biển báo đường dành cho người đi bộ.” — Chọn phát biểu của An:",
      image: asset("images/slide-pedestrian.jpg"),
      quiz: {
        kind: "single",
        correct: 1,
        explain: "Phủ định của Khoa: “Đây <strong>không phải</strong> là biển báo đường dành cho người đi bộ.”",
        options: [
          { html: "Biển báo này đẹp quá!" },
          { html: "Đây không phải là biển báo đường dành cho người đi bộ." },
          { html: "Có phải biển người đi bộ không?" },
        ],
      },
    },
    {
      type: "content",
      title: "Mệnh đề phủ định",
      banner: "Phần 2 · Chốt kiến thức",
      bannerTone: "orange",
      heading: "Mệnh đề phủ định",
      definition: "Phủ định của \\(P\\) kí hiệu \\(\\overline{P}\\) (hoặc \\(\\neg P\\)): đúng/sai <em>trái ngược</em> với \\(P\\).",
      image: asset("images/sgk-no-car.jpg"),
      bullets: ["Thường thêm/bớt “không”, “không phải”.", "Nếu \\(P\\) đúng thì \\(\\overline{P}\\) sai, và ngược lại."],
      callout: "Ví dụ: \\(P\\): “2022 chia hết cho 5” → \\(\\overline{P}\\): “2022 không chia hết cho 5”.",
    },
    {
      type: "quiz",
      title: "Kéo theo",
      banner: "Phần 3 · Tương tác",
      bannerTone: "teal",
      heading: "Mệnh đề kéo theo này đúng hay sai?",
      image: asset("images/sgk-redlight.jpg"),
      quiz: {
        kind: "single",
        correct: 0,
        explain:
          "Mệnh đề kéo theo đúng: tiền đề đúng và kết luận đúng. “Nếu An vượt đèn đỏ thì An vi phạm luật giao thông.” là mệnh đề đúng.",
        options: [{ html: "Đúng" }, { html: "Sai" }],
      },
    },
    {
      type: "content",
      title: "Cần · đủ · Đảo",
      banner: "Phần 3 · Chốt kiến thức",
      bannerTone: "teal",
      heading: "Điều kiện cần · đủ · Mệnh đề đảo",
      parts: [
        { n: "Đủ", title: "\\(P\\) đủ cho \\(Q\\)", text: "Có \\(P\\) thì chắc có \\(Q\\)", color: "#14b8a6" },
        { n: "Cần", title: "\\(Q\\) cần cho \\(P\\)", text: "Muốn có \\(P\\) thì phải có \\(Q\\)", color: "#f97316" },
        { n: "Đảo", title: "\\(Q \\Rightarrow P\\)", text: "Đảo của kéo theo — có thể sai!", color: "#8b5cf6" },
      ],
      callout: "Ví dụ đảo sai: “Nếu tam giác cân thì tam giác đều” — sai vì cân chỉ cần hai cạnh bằng nhau.",
    },
    {
      type: "content",
      title: "Tương đương",
      banner: "Phần 4",
      bannerTone: "violet",
      heading: "Mệnh đề tương đương",
      definition: "“\\(P\\) nếu và chỉ nếu \\(Q\\)” kí hiệu \\(P \\Leftrightarrow Q\\).",
      bullets: [
        "Đúng khi cả \\(P \\Rightarrow Q\\) và \\(Q \\Rightarrow P\\) đều đúng.",
        "Nói: \\(P\\) là <strong>điều kiện cần và đủ</strong> để có \\(Q\\).",
      ],
      tags: ["Chữ số tận cùng chẵn ⇔ chia hết cho 2", "Khi và chỉ khi"],
    },
    {
      type: "content",
      title: "Lượng từ ∀ ∃",
      banner: "Phần 5",
      bannerTone: "rose",
      heading: "Mệnh đề chứa \\(\\forall\\), \\(\\exists\\)",
      image: asset("images/sgk-forall.jpg"),
      bullets: ["\\(\\forall\\): <strong>với mọi</strong>", "\\(\\exists\\): <strong>tồn tại</strong> (có ít nhất một)"],
      definition:
        "“Mọi số tự nhiên nhân với 1 đều bằng chính nó.” → đúng.<br/>Phủ định: “Có một số tự nhiên nhân với 1 không bằng chính nó.” → sai.",
    },
    {
      type: "content",
      title: "Phủ định lượng từ",
      banner: "Phần 5 · Chốt kiến thức",
      bannerTone: "rose",
      heading: "Cách phủ định \\(\\forall\\) và \\(\\exists\\)",
      definition:
        "\\(\\overline{\\forall x,\\; P(x)} \\;=\\; \\exists x,\\; \\overline{P(x)}\\)<br/>\\(\\overline{\\exists x,\\; P(x)} \\;=\\; \\forall x,\\; \\overline{P(x)}\\)",
      parts: [
        { n: "∀", title: "“Mọi…”", text: "Phủ định → “Có ít nhất một… không…”", color: "#e11d48" },
        { n: "∃", title: "“Có ít nhất…”", text: "Phủ định → “Mọi… không…”", color: "#2563eb" },
      ],
    },
    {
      type: "summary",
      title: "Tóm tắt",
      banner: "Tổng kết",
      bannerTone: "blue",
      heading: "Nhớ nhanh 5 ý chính",
      ctaLabel: "Sang Challenge Map →",
      parts: [
        { n: "1", title: "Mệnh đề", text: "Đúng hoặc sai", color: "#2563eb" },
        { n: "2", title: "Phủ định", text: "\\(\\overline{P}\\)", color: "#f97316" },
        { n: "3", title: "Kéo theo · Đảo", text: "\\(P \\Rightarrow Q\\)", color: "#14b8a6" },
        { n: "4", title: "Tương đương", text: "\\(P \\Leftrightarrow Q\\)", color: "#8b5cf6" },
        { n: "5", title: "∀ · ∃", text: "Phủ định đổi chỗ", color: "#e11d48" },
      ],
    },
  ],
  challenges: [
    {
      level: 1,
      title: "Không phải mệnh đề",
      image: asset("images/quiz-truefalse.jpg"),
      prompt: "Trong các câu sau, câu nào <strong>không</strong> phải mệnh đề?",
      options: [
        "Số 5 là số nguyên dương.",
        "Số 15 là số nguyên tố.",
        "Cố lên, sắp đến rồi!",
        "Tổng các góc của một tam giác là \\(180^\\circ\\).",
      ],
      answer: 2,
      explain: "“Cố lên, sắp đến rồi!” là câu cảm thán — không có tính đúng/sai logic.",
    },
    {
      level: 1,
      title: "Biển báo giao thông",
      image: asset("images/quiz-traffic.jpg"),
      prompt: "Quan sát tình huống giao thông: câu nào là <strong>mệnh đề đúng</strong>?",
      options: [
        "Biển cấm ô tô có đẹp không?",
        "Khu vực có biển cấm ô tô thì ô tô không được đi vào.",
        "Hãy chú ý biển báo!",
        "Ô tô có nên đi vào không?",
      ],
      answer: 1,
      explain: "Chỉ câu khẳng định đúng/sai mới là mệnh đề. Câu B đúng theo luật giao thông.",
    },
    {
      level: 1,
      title: "Đọc kéo theo",
      prompt:
        "Cho \\(P\\): “4 là số chẵn” và \\(Q\\): “Hà Nội là thủ đô Việt Nam”. Phát biểu của \\(P \\Rightarrow Q\\) là:",
      options: [
        "Nếu 4 là số chẵn thì Hà Nội là thủ đô của Việt Nam.",
        "Nếu Hà Nội là thủ đô của Việt Nam thì 4 là số chẵn.",
        "4 là số chẵn nếu Hà Nội là thủ đô của Việt Nam.",
        "Nếu 4 là số chẵn thì Hà Nội không là thủ đô của Việt Nam.",
      ],
      answer: 0,
      explain: "\\(P \\Rightarrow Q\\) đọc là “Nếu \\(P\\) thì \\(Q\\)”.",
    },
    {
      level: 1,
      title: "Phủ định cơ bản",
      prompt: "Mệnh đề phủ định của “Phương trình \\(x^2 + 1 = 0\\) vô nghiệm” (trên \\(\\mathbb{R}\\)) là:",
      options: [
        "Phương trình không có nghiệm.",
        "Phương trình có 2 nghiệm phân biệt.",
        "Phương trình có nghiệm kép.",
        "Phương trình có nghiệm.",
      ],
      answer: 3,
      explain: "Phủ định của “vô nghiệm” là “có nghiệm”.",
    },
    {
      level: 1,
      title: "Chứa biến",
      prompt: "Câu nào là mệnh đề chứa biến?",
      options: ["\\(2\\) là số nguyên tố.", "\\(x + 3 &gt; 5\\)", "Hà Nội là thủ đô Việt Nam.", "Bạn thích Toán không?"],
      answer: 1,
      explain: "“\\(x + 3 &gt; 5\\)” chứa biến \\(x\\); khi thay giá trị cụ thể mới thành mệnh đề đúng/sai.",
    },
    {
      level: 2,
      title: "Mệnh đề đảo",
      image: asset("images/quiz-implication.jpg"),
      prompt: "Cho mệnh đề: “Nếu hai tứ giác bằng nhau thì diện tích bằng nhau”. Mệnh đề đảo là:",
      options: [
        "Nếu hai tứ giác có diện tích bằng nhau thì chúng bằng nhau.",
        "Nếu hai tứ giác không bằng nhau thì diện tích không bằng nhau.",
        "Hai tứ giác bằng nhau khi và chỉ khi diện tích bằng nhau.",
        "Nếu diện tích không bằng nhau thì hai tứ giác không bằng nhau.",
      ],
      answer: 0,
      explain: "Đảo của \\(P \\Rightarrow Q\\) là \\(Q \\Rightarrow P\\).",
    },
    {
      level: 2,
      title: "Phủ định ∀",
      image: asset("images/quiz-quantifiers.jpg"),
      prompt: "Phủ định của \\(\\forall x \\in \\mathbb{R},\\; x^2 \\ge 0\\) là:",
      options: [
        "\\(\\exists x \\in \\mathbb{R},\\; x^2 &lt; 0\\)",
        "\\(\\forall x \\in \\mathbb{R},\\; x^2 &lt; 0\\)",
        "\\(\\exists x \\in \\mathbb{R},\\; x^2 \\ge 0\\)",
        "\\(\\forall x \\in \\mathbb{R},\\; x^2 &gt; 0\\)",
      ],
      answer: 0,
      explain: "\\(\\overline{\\forall x,\\, P(x)} = \\exists x,\\, \\overline{P(x)}\\).",
    },
    {
      level: 2,
      title: "Chọn mệnh đề đúng",
      prompt: "Mệnh đề nào dưới đây đúng?",
      options: [
        "Một số nguyên dương chia hết cho 3 khi và chỉ khi tổng các chữ số của nó chia hết cho 3.",
        "Hai tam giác bằng nhau khi và chỉ khi chúng có diện tích bằng nhau.",
        "\\(a + b\\) chia hết cho 7 khi và chỉ khi \\(a\\) và \\(b\\) cùng chia hết cho 7.",
        "Nếu \\(x &gt; 2\\) thì \\(x^2 &gt; 4\\) có mệnh đề đảo luôn đúng.",
      ],
      answer: 0,
      explain: "Dấu hiệu chia hết cho 3 là điều kiện cần và đủ.",
    },
    {
      level: 2,
      title: "Điều kiện cần",
      prompt: "Với định lí “Nếu \\(n\\) chia hết cho \\(15\\) thì \\(n\\) chia hết cho \\(5\\)”, khẳng định nào đúng?",
      options: [
        "Chia hết cho 15 là điều kiện cần để chia hết cho 5.",
        "Chia hết cho 5 là điều kiện đủ để chia hết cho 15.",
        "Chia hết cho 5 là điều kiện cần để chia hết cho 15.",
        "Hai điều kiện tương đương.",
      ],
      answer: 2,
      explain: "Với \\(P \\Rightarrow Q\\): \\(Q\\) là điều kiện cần của \\(P\\).",
    },
    {
      level: 3,
      title: "Phủ định “có ít nhất”",
      prompt: "Phủ định của “Có ít nhất một số vô tỉ là số thập phân vô hạn tuần hoàn” là:",
      options: [
        "Mọi số vô tỉ đều là số thập phân vô hạn không tuần hoàn.",
        "Mọi số vô tỉ đều là số thập phân tuần hoàn.",
        "Mọi số vô tỉ đều là số thập phân vô hạn tuần hoàn.",
        "Có ít nhất một số vô tỉ là số thập phân vô hạn không tuần hoàn.",
      ],
      answer: 0,
      explain: "Phủ định “có ít nhất một…” là “mọi… không…”.",
    },
    {
      level: 3,
      title: "Hai kéo theo",
      image: asset("images/quiz-implication.jpg"),
      prompt:
        "Xét \\(P \\Rightarrow Q\\): “Nếu 18 chia hết cho 3 thì tam giác cân có 2 cạnh bằng nhau” và \\(R \\Rightarrow S\\): “Nếu 17 là số chẵn thì 25 là số chính phương”. Khẳng định đúng?",
      options: [
        "\\(P \\Rightarrow Q\\) đúng, \\(R \\Rightarrow S\\) sai.",
        "\\(P \\Rightarrow Q\\) đúng, \\(R \\Rightarrow S\\) đúng.",
        "\\(P \\Rightarrow Q\\) sai, \\(R \\Rightarrow S\\) đúng.",
        "Cả hai đều sai.",
      ],
      answer: 1,
      explain: "Kéo theo chỉ sai khi tiền đề đúng và hậu quả sai. Cả hai kéo theo đều đúng.",
    },
    {
      level: 3,
      title: "Phủ định ∀ trên N",
      prompt: "Cho mệnh đề \\(\\forall x \\in \\mathbb{N},\\; x(x+1)\\) chẵn. Mệnh đề phủ định và tính đúng/sai của phủ định?",
      options: [
        "\\(\\exists x \\in \\mathbb{N},\\; x(x+1)\\) lẻ — phủ định sai.",
        "\\(\\forall x \\in \\mathbb{N},\\; x(x+1)\\) lẻ — phủ định đúng.",
        "\\(\\exists x \\in \\mathbb{N},\\; x(x+1)\\) lẻ — phủ định đúng.",
        "\\(\\exists x \\in \\mathbb{N},\\; x(x+1)\\) chẵn — phủ định sai.",
      ],
      answer: 0,
      explain: "Phủ định là tồn tại \\(x\\) sao cho tích lẻ — nhưng tích hai số liên tiếp luôn chẵn nên phủ định sai.",
    },
    {
      level: 4,
      title: "Đảo nào đúng?",
      prompt: "Trong các mệnh đề sau, mệnh đề nào có <strong>mệnh đề đảo đúng</strong>?",
      options: [
        "Nếu \\(M\\) là trung điểm \\(BC\\) thì \\(AB = AC\\).",
        "Nếu \\(ABCD\\) là hình bình hành thì \\(AB \\parallel CD\\).",
        "Nếu \\(x &gt; 2\\) thì \\(x^2 &gt; 4\\).",
        "Nếu \\(m,n\\) nguyên dương cùng chia hết cho 3 thì \\(m^2 + n^2\\) chia hết cho 3.",
      ],
      answer: 3,
      explain: "Đảo của D đúng (modulo 3). Các đảo còn lại đều có phản ví dụ.",
    },
    {
      level: 4,
      title: "Chọn mệnh đề sai",
      image: asset("images/quiz-quantifiers.jpg"),
      prompt: "Chọn mệnh đề <strong>sai</strong>:",
      options: [
        "\\(\\forall a \\in \\mathbb{Z},\\; \\exists b \\in \\mathbb{Z}: a + b\\) là số nguyên.",
        "\\(\\forall x &gt; 0,\\; \\exists y &gt; 0: xy = 1\\).",
        "\\(\\forall n \\in \\mathbb{N},\\; n^2 + n + 1\\) là số nguyên tố.",
        "\\(\\exists x \\in \\mathbb{R}: x^2 = 2\\).",
      ],
      answer: 2,
      explain: "Với \\(n = 4\\): \\(21\\) không nguyên tố. Các mệnh đề còn lại đúng.",
    },
  ],
};
