import { asset } from "../lib/asset";
import type { Lesson } from "../lib/schema";

export const bai2: Lesson = {
  id: "bai-2",
  number: 2,
  slug: "tap-hop",
  title: "Tập hợp",
  shortTitle: "Tập hợp",
  chapter: "Chương I",
  periods: 4,
  blurb: "Đảo Tập Hợp · Ven tương tác · ∩ ∪ ∖",
  theme: {
    id: "island",
    accentFrom: "#22d3ee",
    accentTo: "#6366f1",
    mapBoardClass: "map-board--island",
    nodeClass: "map-node__btn--island",
    xpLabel: "Ngọc",
    mapName: "Đảo Tập Hợp",
    sectionPrefix: "Quần đảo",
    chestClosed: "🪸",
    chestOpen: "🏝️",
    successText: "Cập bến!",
    failText: "Sóng đánh trôi.",
    lockedToast: "Còn sóng chắn — hãy mở mốc trước!",
    resetLabel: "Khám phá lại",
    resetConfirm: "Xóa tiến độ Đảo Tập Hợp?",
    brandMark: "venn",
  },
  progressKey: "toan-thpt-island-taphop-v1",
  levelLabels: { 1: "Khái niệm", 2: "Tập con", 3: "Tập số", 4: "Phép toán" },
  xpByLevel: { 1: 12, 2: 16, 3: 20, 4: 28 },
  sidebarFoot: "Theo dõi Club Lịch sử · bấm vùng Venn để khám phá phép toán.",
  slides: [
    {
      type: "hero",
      title: "Đảo Tập Hợp",
      eyebrow: "Toán 10 · Chương I · 4 tiết",
      heading: "Bài 2. Tập hợp &amp; phép toán",
      body: "Không học khô: lần này ta phá án Club Lịch sử — ai vắng chuyên đề? Ai thuộc giao hai tập?",
      image: asset("images/bai2/venn-islands.jpg"),
      imageAlt: "Đảo Tập Hợp",
    },
    {
      type: "quiz",
      title: "Án Club Lịch sử",
      banner: "Nhiệm vụ mở đầu · Tương tác",
      bannerTone: "cyan",
      heading: "Club Lịch sử · 12 thành viên",
      prompt:
        "Hai chuyên đề trên phần mềm học trực tuyến. Theo giáo án: CD1 vắng 5, CD2 vắng 4. Hỏi số bạn <strong>tham gia CD1</strong> là?",
      image: asset("images/bai2/history-club.jpg"),
      quiz: {
        kind: "single",
        correct: 1,
        explain:
          "Club có 12 thành viên. Chuyên đề 1 vắng 5 → có 7 bạn tham gia. Chuyên đề 2 vắng 4 → có 8 bạn tham gia.",
        options: [{ html: "5 bạn" }, { html: "7 bạn" }, { html: "8 bạn" }, { html: "12 bạn" }],
      },
    },
    {
      type: "content",
      title: "Lộ trình 4 đảo",
      banner: "Bản đồ kiến thức",
      bannerTone: "indigo",
      heading: "Bốn hòn đảo cần chinh phục",
      image: asset("images/bai2/sgk-2.jpg"),
      parts: [
        { n: "1", title: "Khái niệm", text: "Phần tử · liệt kê · tính chất · ∅", color: "#06b6d4" },
        { n: "2", title: "Tập con · =", text: "⊂ · biểu đồ Ven", color: "#8b5cf6" },
        { n: "3", title: "Tập số", text: "N ⊂ Z ⊂ Q ⊂ R · khoảng", color: "#10b981" },
        { n: "4", title: "Phép toán", text: "∩ ∪ ∖ · phần bù", color: "#ec4899" },
      ],
    },
    {
      type: "content",
      title: "Tập hợp là gì?",
      banner: "Đảo 1 · Khái niệm",
      bannerTone: "cyan",
      heading: "Tập hợp &amp; phần tử",
      definition:
        "Tập hợp là một nhóm các đối tượng xác định. Mỗi đối tượng trong nhóm gọi là <strong>phần tử</strong>.",
      bullets: [
        "\\(a \\in A\\): \\(a\\) thuộc \\(A\\)",
        "\\(a \\notin A\\): \\(a\\) không thuộc \\(A\\)",
        "Hai cách mô tả: <strong>liệt kê</strong> hoặc <strong>tính chất đặc trưng</strong>",
        "Tập không có phần tử: tập rỗng \\(\\varnothing\\), \\(|\\varnothing| = 0\\)",
      ],
      tags: ["A = {Nam, Lan, …}", "B = {x | x là châu lục}"],
    },
    {
      type: "quiz",
      title: "Thuộc hay không?",
      banner: "Đảo 1 · Tương tác",
      bannerTone: "cyan",
      heading: "Gọi S là tập nghiệm thực của \\(x^2 + 1 = 0\\)",
      quiz: {
        kind: "single",
        correct: 2,
        explain: "Nghiệm của \\(x^2 + 1 = 0\\) trên \\(\\mathbb{R}\\) là tập rỗng → không có phần tử nào thuộc tập nghiệm.",
        options: [
          { html: "\\(0 \\in S\\)" },
          { html: "\\(1 \\in S\\)" },
          { html: "\\(S = \\varnothing\\)" },
          { html: "\\(|S| = 2\\)" },
        ],
      },
    },
    {
      type: "content",
      title: "Tập con",
      banner: "Đảo 2",
      bannerTone: "indigo",
      heading: "Tập con &amp; hai tập bằng nhau",
      image: asset("images/bai2/sgk-2.jpg"),
      definition:
        "\\(T \\subset S\\) nếu mọi phần tử của \\(T\\) đều thuộc \\(S\\).<br/>\\(S = T\\) khi \\(S \\subset T\\) và \\(T \\subset S\\).",
      bullets: ["\\(\\varnothing\\) là tập con của mọi tập hợp", "\\(S \\subset S\\) luôn đúng"],
    },
    {
      type: "quiz",
      title: "Hình vuông ⊂ ?",
      banner: "Đảo 2 · Tương tác",
      bannerTone: "indigo",
      heading: "C = {hình bình hành có đường chéo ⊥}, D = {hình vuông}",
      quiz: {
        kind: "single",
        correct: 1,
        explain:
          "Mọi hình vuông đều là hình bình hành có hai đường chéo vuông góc → \\(D \\subset C\\). Chiều ngược lại sai (hình thoi chưa chắc là hình vuông).",
        options: [
          { html: "\\(C \\subset D\\)" },
          { html: "\\(D \\subset C\\)" },
          { html: "\\(C = D\\)" },
          { html: "\\(D \\not\\subset C\\)" },
        ],
      },
    },
    {
      type: "content",
      title: "Các tập số",
      banner: "Đảo 3",
      bannerTone: "cyan",
      heading: "Chuỗi bao hàm tập số",
      nests: [
        '<span class="nest-dot" style="background:#22d3ee"></span>\\(\\mathbb{N}\\) · số tự nhiên',
        '<span class="nest-dot" style="background:#818cf8"></span>\\(\\mathbb{Z}\\) · số nguyên · \\(\\mathbb{N} \\subset \\mathbb{Z}\\)',
        '<span class="nest-dot" style="background:#a78bfa"></span>\\(\\mathbb{Q}\\) · số hữu tỉ · \\(\\mathbb{Z} \\subset \\mathbb{Q}\\)',
        '<span class="nest-dot" style="background:#f472b6"></span>\\(\\mathbb{R}\\) · số thực · \\(\\mathbb{Q} \\subset \\mathbb{R}\\)',
      ],
      callout: "Khoảng \\((a;b)\\), đoạn \\([a;b]\\), nửa khoảng \\([a;b)\\), \\((a;+\\infty)\\)…",
    },
    {
      type: "quiz",
      title: "Ghép khoảng",
      banner: "Đảo 3 · Tương tác",
      bannerTone: "cyan",
      heading: "\\(x \\in [2;5]\\) tương đương với?",
      image: asset("images/bai2/sgk-3.jpg"),
      quiz: {
        kind: "single",
        correct: 3,
        explain: "\\(x \\in [2;5]\\) nghĩa là \\(2 \\le x \\le 5\\).",
        options: [
          { html: "\\(2 &lt; x \\le 5\\)" },
          { html: "\\(2 \\le x &lt; 5\\)" },
          { html: "\\(2 &lt; x &lt; 5\\)" },
          { html: "\\(2 \\le x \\le 5\\)" },
        ],
      },
    },
    {
      type: "quiz",
      title: "Phòng lab Venn",
      banner: "Đảo 4 · Lab Ven · Tương tác",
      bannerTone: "indigo",
      heading: "Bấm vào vùng = thành viên tham gia <em>cả hai</em> chuyên đề",
      quiz: {
        kind: "venn",
        correct: ["inter"],
        explain: "Vùng giao (∩) gồm phần tử thuộc <strong>cả A và B</strong> — chính là những bạn tham gia cả hai chuyên đề.",
      },
    },
    {
      type: "content",
      title: "∩ ∪ ∖",
      banner: "Đảo 4 · Chốt kiến thức",
      bannerTone: "indigo",
      heading: "Ba phép toán vàng",
      parts: [
        { n: "∩", title: "Giao", text: "Thuộc cả S và T", color: "#10b981" },
        { n: "∪", title: "Hợp", text: "Thuộc S hoặc T", color: "#06b6d4" },
        { n: "∖", title: "Hiệu", text: "Thuộc S, không thuộc T", color: "#f59e0b" },
        { n: "∁", title: "Phần bù", text: "Nếu T ⊂ S thì S∖T = C_S(T)", color: "#ec4899" },
      ],
      definition: "Công thức đếm: \\(|A \\cup B| = |A| + |B| - |A \\cap B|\\)",
    },
    {
      type: "quiz",
      title: "Bóng đá & cầu lông",
      banner: "Vận dụng · Tương tác",
      bannerTone: "cyan",
      heading: "24 bạn chơi bóng đá hoặc cầu lông; 16 đá bóng, 11 cầu lông. Bao nhiêu bạn chơi cả hai?",
      quiz: {
        kind: "single",
        correct: 0,
        explain: "|A∪B|=24, |A|=16, |B|=11 → |A∩B| = 16+11-24 = 3 bạn chơi cả hai.",
        options: [{ html: "3" }, { html: "5" }, { html: "8" }, { html: "27" }],
      },
    },
    {
      type: "summary",
      title: "Tóm tắt đảo",
      banner: "Kho báu kiến thức",
      bannerTone: "indigo",
      heading: "Nhớ nhanh trước khi ra đảo Challenge",
      ctaLabel: "Vào Đảo Tập Hợp →",
      parts: [
        { n: "∈", title: "Thuộc", text: "Phần tử · ∅", color: "#06b6d4" },
        { n: "⊂", title: "Tập con", text: "Ven · bằng nhau", color: "#8b5cf6" },
        { n: "R", title: "Tập số", text: "N⊂Z⊂Q⊂R", color: "#10b981" },
        { n: "∪", title: "Phép toán", text: "|A∪B|=|A|+|B|−|A∩B|", color: "#ec4899" },
      ],
    },
  ],
  challenges: [
    {
      level: 1,
      title: "Club vắng mặt",
      image: asset("images/bai2/history-club.jpg"),
      prompt: "Club 12 thành viên, chuyên đề 2 vắng 4 bạn. Số bạn tham gia chuyên đề 2 là?",
      options: ["4", "8", "12", "16"],
      answer: 1,
      explain: "12 − 4 = 8 bạn tham gia chuyên đề 2.",
    },
    {
      level: 1,
      title: "Tập rỗng",
      prompt: "Tập nghiệm thực của \\(x^2 + 1 = 0\\) là?",
      options: ["\\{0\\}", "\\{1, -1\\}", "\\(\\varnothing\\)", "\\(\\mathbb{R}\\)"],
      answer: 2,
      explain: "Phương trình vô nghiệm trên \\(\\mathbb{R}\\) → tập rỗng.",
    },
    {
      level: 1,
      title: "Cách mô tả",
      prompt: "Một tập hợp có thể được mô tả bởi mấy cách chính?",
      options: ["1 cách", "2 cách (liệt kê / tính chất)", "3 cách", "Không giới hạn và không phân loại"],
      answer: 1,
      explain: "Hai cách: liệt kê phần tử, hoặc chỉ ra tính chất đặc trưng.",
    },
    {
      level: 2,
      title: "Tập con hình học",
      prompt: "D = {hình vuông}, C = {hình bình hành có đường chéo ⊥}. Mệnh đề đúng?",
      options: ["\\(C \\subset D\\)", "\\(D \\subset C\\)", "\\(C = D\\)", "\\(D \\not\\subset C\\)"],
      answer: 1,
      explain: "Hình vuông luôn thuộc C; chiều ngược lại sai.",
    },
    {
      level: 2,
      title: "Tập rỗng ⊂ ?",
      prompt: "Khẳng định nào đúng?",
      options: [
        "\\(\\varnothing\\) không là tập con của bất kỳ tập nào",
        "\\(\\varnothing \\subset A\\) với mọi tập A",
        "\\(|\\varnothing| = 1\\)",
        "\\(\\varnothing = \\{0\\}\\)",
      ],
      answer: 1,
      explain: "Tập rỗng là tập con của mọi tập hợp.",
    },
    {
      level: 2,
      title: "Hai tập bằng nhau",
      prompt: "S = T khi nào?",
      options: ["Chỉ cần \\(S \\subset T\\)", "Chỉ cần |S| = |T|", "\\(S \\subset T\\) và \\(T \\subset S\\)", "S và T giao nhau"],
      answer: 2,
      explain: "Hai tập bằng nhau khi mỗi cái là tập con của cái kia.",
    },
    {
      level: 3,
      title: "Chuỗi bao hàm",
      prompt: "Mệnh đề đúng?",
      options: [
        "\\(\\mathbb{R} \\subset \\mathbb{Q}\\)",
        "\\(\\mathbb{Z} \\subset \\mathbb{N}\\)",
        "\\(\\mathbb{N} \\subset \\mathbb{Z} \\subset \\mathbb{Q} \\subset \\mathbb{R}\\)",
        "\\(\\mathbb{Q} \\subset \\mathbb{Z}\\)",
      ],
      answer: 2,
      explain: "Chuỗi bao hàm chuẩn của các tập số.",
    },
    {
      level: 3,
      title: "Đoạn [2;5]",
      image: asset("images/bai2/sgk-3.jpg"),
      prompt: "\\(x \\in [2;5]\\) tương đương?",
      options: ["\\(2 < x < 5\\)", "\\(2 \\le x < 5\\)", "\\(2 < x \\le 5\\)", "\\(2 \\le x \\le 5\\)"],
      answer: 3,
      explain: "Ngoặc vuông = lấy cả hai đầu mút.",
    },
    {
      level: 3,
      title: "Số vô tỉ",
      prompt: "Khẳng định đúng?",
      options: ["Mọi số thực đều hữu tỉ", "Tồn tại số thực không hữu tỉ", "\\(\\mathbb{Q} = \\mathbb{R}\\)", "Không có số vô tỉ"],
      answer: 1,
      explain: "Ví dụ \\(\\sqrt{2}\\), \\(\\pi\\) là vô tỉ.",
    },
    {
      level: 4,
      title: "Giao hai tập",
      image: asset("images/bai2/venn-islands.jpg"),
      prompt: "A = {1,2,3,4}, B = {3,4,5}. A ∩ B bằng?",
      options: ["{1,2}", "{3,4}", "{1,2,3,4,5}", "{5}"],
      answer: 1,
      explain: "Giao = phần tử thuộc cả hai tập: 3 và 4.",
    },
    {
      level: 4,
      title: "Hợp & đếm",
      prompt: "|A|=16, |B|=11, |A∪B|=24. |A∩B| bằng?",
      options: ["3", "5", "8", "27"],
      answer: 0,
      explain: "|A∩B| = |A|+|B|−|A∪B| = 16+11−24 = 3.",
    },
    {
      level: 4,
      title: "Hiệu tập hợp",
      prompt: "A∖B gồm những phần tử nào?",
      options: [
        "Thuộc A hoặc B",
        "Thuộc cả A và B",
        "Thuộc A nhưng không thuộc B",
        "Không thuộc A và không thuộc B",
      ],
      answer: 2,
      explain: "Hiệu A∖B = phần tử chỉ thuộc A.",
    },
    {
      level: 4,
      title: "Thời tiết xấu",
      prompt: "Mưa 10, gió 8, lạnh 6; mưa∩gió 5; mưa∩lạnh 4; lạnh∩gió 3; cả ba 1. Số ngày xấu (mưa∨gió∨lạnh)?",
      options: ["10", "13", "15", "24"],
      answer: 1,
      explain: "|A∪B∪C| = 10+8+6 −5−4−3 +1 = 13.",
    },
  ],
};
