import { asset } from "../lib/asset";
import type { Lesson } from "../lib/schema";

export const bai3: Lesson = {
  id: "bai-3",
  number: 3,
  slug: "bpt-hai-an",
  title: "Bất phương trình bậc nhất hai ẩn",
  shortTitle: "BPT hai ẩn",
  chapter: "Chương I",
  periods: 3,
  blurb: "Rạp Chiếu Phim · miền nghiệm click",
  isNew: true,
  theme: {
    id: "cinema",
    accentFrom: "#fb923c",
    accentTo: "#e11d48",
    mapBoardClass: "map-board--cinema",
    nodeClass: "map-node__btn--cinema",
    xpLabel: "Vé Vàng",
    mapName: "Rạp Nghiệm",
    sectionPrefix: "Suất",
    chestClosed: "🎫",
    chestOpen: "🍿",
    successText: "Suất chiếu thành công!",
    failText: "Cắt! Quay lại.",
    lockedToast: "Hết vé suất này — mở mốc trước!",
    resetLabel: "Chiếu lại từ đầu",
    resetConfirm: "Xóa tiến độ Rạp Nghiệm?",
    brandMark: "cinema",
  },
  progressKey: "toan-thpt-cinema-bpt-v2",
  levelLabels: { 1: "Định nghĩa", 2: "Nghiệm", 3: "Miền nghiệm", 4: "Vận dụng" },
  xpByLevel: { 1: 12, 2: 16, 3: 22, 4: 32 },
  sidebarFoot: "Lập BPT từ tình huống vé · bấm nửa mặt phẳng để chọn miền nghiệm.",
  slides: [
    {
      type: "hero",
      title: "Rạp Chiếu Phim",
      eyebrow: "Toán 10 · 3 tiết",
      heading: "Bài 3. Bất phương trình bậc nhất hai ẩn",
      body: "Ngày 1/6 · rạp phim hoạt hình · bao nhiêu vé thì không bù lỗ? Đó chính là BPT hai ẩn.",
      image: asset("images/bai3/cinema.jpg"),
      imageAlt: "Rạp chiếu phim",
    },
    {
      type: "quiz",
      title: "Tình huống vé",
      banner: "Mở đầu · Tương tác",
      bannerTone: "amber",
      heading: "Vé loại 1: 50k · Vé loại 2: 100k · Cần ≥ 20 triệu để không lỗ",
      prompt:
        "Gọi \\(x\\) = số vé loại 1 (50&nbsp;000đ), \\(y\\) = số vé loại 2 (100&nbsp;000đ). Rạp <strong>bù lỗ</strong> khi doanh thu <em>nhỏ hơn</em> 20&nbsp;000&nbsp;000 đồng. Bất phương trình nào mô tả đúng điều kiện đó?",
      image: asset("images/bai3/sgk-1.jpg"),
      quiz: {
        kind: "single",
        correct: 1,
        explain:
          "Doanh thu = \\(50000x + 100000y\\). Bù lỗ khi doanh thu &lt; 20 triệu → \\(50000x + 100000y &lt; 20000000\\).",
        options: [
          { html: "\\(50000x + 100000y = 20000000\\)" },
          { html: "\\(50000x + 100000y &lt; 20000000\\)" },
          { html: "\\(x + y &lt; 20\\)" },
          { html: "\\(x &gt; y\\)" },
        ],
      },
    },
    {
      type: "content",
      title: "Lộ trình 3 tập",
      banner: "Suất chiếu kiến thức",
      bannerTone: "rose",
      heading: "Ba tập phim hôm nay",
      image: asset("images/bai3/halfplane.jpg"),
      parts: [
        { n: "1", title: "Định nghĩa", text: "Dạng \\(ax+by+c \\lessgtr 0\\)", color: "#f97316" },
        { n: "2", title: "Nghiệm", text: "Cặp \\((x_0;y_0)\\) làm BPT đúng", color: "#e11d48" },
        { n: "3", title: "Miền nghiệm", text: "Nửa mặt phẳng trên tọa độ", color: "#7c3aed" },
      ],
    },
    {
      type: "content",
      title: "Định nghĩa",
      banner: "Tập 1",
      bannerTone: "amber",
      heading: "Bất phương trình bậc nhất hai ẩn",
      definition:
        "Dạng tổng quát: \\(ax + by + c &lt; 0\\) (hoặc \\(&gt;, \\le, \\ge\\)), trong đó \\(a,b,c \\in \\mathbb{R}\\), \\(a\\) và \\(b\\) <strong>không đồng thời bằng 0</strong>, \\(x,y\\) là ẩn.",
      bullets: [
        "\\((x_0; y_0)\\) là nghiệm nếu thay vào làm bất đẳng thức đúng.",
        "BPT bậc nhất hai ẩn luôn có <strong>vô số nghiệm</strong>.",
      ],
    },
    {
      type: "quiz",
      title: "Nhận biết BPT",
      banner: "Tập 1 · Tương tác",
      bannerTone: "amber",
      heading: "Biểu thức nào là bất phương trình bậc nhất hai ẩn?",
      quiz: {
        kind: "single",
        correct: 0,
        explain:
          "\\(2x - y + 1 &lt; 0\\) đúng dạng bậc nhất hai ẩn. \\(x^2 + y &lt; 1\\) có \\(x^2\\). \\(x+3=0\\) là phương trình một ẩn. \\(xy-2&gt;0\\) có tích \\(xy\\).",
        options: [
          { html: "\\(2x - y + 1 &lt; 0\\)" },
          { html: "\\(x^2 + y &lt; 1\\)" },
          { html: "\\(x + 3 = 0\\) (phương trình một ẩn)" },
          { html: "\\(xy - 2 &gt; 0\\)" },
        ],
      },
    },
    {
      type: "quiz",
      title: "Kiểm tra nghiệm",
      banner: "Tập 2 · Tương tác",
      bannerTone: "rose",
      heading: "Cho BPT \\(x - 2y + 1 &lt; 0\\). Cặp số nào là một nghiệm?",
      prompt: "Hãy thay từng cặp vào vế trái rồi so với 0.",
      quiz: {
        kind: "single",
        correct: 0,
        explain:
          "Với \\(x-2y+1&lt;0\\): \\((0;1)\\) cho \\(-1&lt;0\\) đúng → là nghiệm. \\((0;0)\\) cho \\(1&lt;0\\) sai; \\((3;0)\\) cho \\(4&lt;0\\) sai; \\((2;-1)\\) cho \\(5&lt;0\\) sai.",
        options: [{ html: "\\((0; 1)\\)" }, { html: "\\((0; 0)\\)" }, { html: "\\((3; 0)\\)" }, { html: "\\((2; -1)\\)" }],
      },
    },
    {
      type: "content",
      title: "Miền nghiệm",
      banner: "Tập 3",
      bannerTone: "rose",
      heading: "Miền nghiệm trên mặt phẳng",
      image: asset("images/bai3/sgk-2.jpg"),
      definition: "Tập hợp các điểm \\((x;y)\\) là nghiệm gọi là <strong>miền nghiệm</strong>.",
      bullets: [
        "Đường thẳng \\(ax+by+c=0\\) chia mặt phẳng thành 2 nửa mặt phẳng.",
        "Một nửa thỏa \\(ax+by+c&gt;0\\), nửa kia thỏa \\(&lt;0\\).",
        "Bờ: có kể hay không tùy \\(\\le, \\ge\\) hay \\(&lt;, &gt;\\).",
      ],
    },
    {
      type: "quiz",
      title: "Lab nửa mặt phẳng",
      banner: "Tập 3 · Lab · Tương tác",
      bannerTone: "amber",
      heading: "Cho BPT \\(x + 2y &lt; 400\\). Đường vàng là biên \\(x+2y=400\\).",
      prompt:
        "Thử điểm \\(O(0;0)\\) (không nằm trên biên). Kết quả đúng ⇒ miền nghiệm chứa gốc. Hãy <strong>bấm nửa mặt phẳng chứa gốc</strong> (vùng A — màu cam).",
      quiz: {
        kind: "halfplane",
        correct: "below",
        explain:
          "Thử \\(O(0;0)\\): \\(0+0=0&lt;400\\) đúng ⇒ miền nghiệm của \\(x+2y&lt;400\\) là nửa mặt phẳng <strong>chứa gốc</strong> — vùng A (cam) trong hình.",
      },
    },
    {
      type: "content",
      title: "4 bước vẽ",
      banner: "Kỹ xảo đạo diễn",
      bannerTone: "rose",
      heading: "Biểu diễn miền nghiệm — 4 bước",
      parts: [
        { n: "1", title: "Vẽ bờ", text: "Đường thẳng \\(ax+by+c=0\\)", color: "#f97316" },
        { n: "2", title: "Chọn điểm thử", text: "Không nằm trên bờ (hay dùng O)", color: "#e11d48" },
        { n: "3", title: "Thay &amp; so sánh", text: "Xem bất đẳng thức đúng/sai", color: "#7c3aed" },
        { n: "4", title: "Tô miền", text: "Nửa mặt phẳng thỏa · nhớ bờ", color: "#0ea5e9" },
      ],
      callout: "Mẹo: nếu \\((0;0)\\) thỏa → miền chứa gốc; không thỏa → miền không chứa gốc.",
    },
    {
      type: "quiz",
      title: "Vé không lỗ",
      banner: "Vận dụng · Tương tác",
      bannerTone: "amber",
      heading: "Không lỗ khi \\(x+2y\\ge400\\) (\\(x\\): vé loại 1 · \\(y\\): vé loại 2)",
      prompt: "Rạp đã bán được <strong>80 vé loại 1</strong>. Cần bán <strong>ít nhất</strong> bao nhiêu vé loại 2 để không lỗ?",
      quiz: {
        kind: "single",
        correct: 2,
        explain:
          "Điều kiện không lỗ: \\(x+2y\\ge400\\). Với \\(x=80\\): \\(80+2y\\ge400\\Rightarrow y\\ge160\\). Vậy cần ít nhất 160 vé loại 2.",
        options: [{ html: "120 vé" }, { html: "140 vé" }, { html: "160 vé" }, { html: "200 vé" }],
      },
    },
    {
      type: "quiz",
      title: "Hai điều kiện",
      banner: "Vận dụng nâng cao",
      bannerTone: "rose",
      heading: "Không lỗ \\(x+2y\\ge400\\) và thêm ràng buộc \\(y\\le\\dfrac{x}{2}\\)",
      prompt: "Cặp \\((x;y)\\) nào thỏa <strong>đồng thời</strong> cả hai điều kiện? (\\(x,y\\ge0\\))",
      quiz: {
        kind: "single",
        correct: 1,
        explain:
          "Cần \\(x+2y\\ge400\\) và \\(y\\le x/2\\). Chỉ \\((300;100)\\): \\(300+200=500\\ge400\\) và \\(100\\le150\\). Các cặp khác vi phạm ít nhất một điều kiện.",
        options: [
          { html: "\\((200; 120)\\)" },
          { html: "\\((300; 100)\\)" },
          { html: "\\((100; 200)\\)" },
          { html: "\\((250; 140)\\)" },
        ],
      },
    },
    {
      type: "summary",
      title: "Tóm tắt",
      banner: "Credits kiến thức",
      bannerTone: "rose",
      heading: "Trước khi vào Rạp Nghiệm",
      ctaLabel: "Vào Rạp Nghiệm Challenge →",
      parts: [
        { n: "1", title: "Dạng", text: "\\(ax+by+c \\lessgtr 0\\)", color: "#f97316" },
        { n: "2", title: "Nghiệm", text: "Cặp số làm BPT đúng", color: "#e11d48" },
        { n: "3", title: "Miền", text: "Nửa mặt phẳng", color: "#7c3aed" },
        { n: "4", title: "4 bước", text: "Vẽ · thử · tô", color: "#0ea5e9" },
      ],
    },
  ],
  challenges: [
    {
      level: 1,
      title: "Bù lỗ khi nào?",
      image: asset("images/bai3/cinema.jpg"),
      prompt:
        "Rạp bán vé loại 1 giá 50&nbsp;000 đồng và vé loại 2 giá 100&nbsp;000 đồng. Gọi \\(x,y\\) lần lượt là số vé loại 1 và loại 2 đã bán. Rạp <strong>bù lỗ</strong> khi doanh thu nhỏ hơn 20&nbsp;000&nbsp;000 đồng. Bất phương trình nào mô tả đúng điều kiện bù lỗ?",
      options: [
        "\\(50000x+100000y=20000000\\)",
        "\\(50000x+100000y&lt;20000000\\)",
        "\\(x+y&lt;20\\)",
        "\\(x&gt;y\\)",
      ],
      answer: 1,
      explain:
        "Doanh thu = \\(50000x+100000y\\). Bù lỗ ⟺ doanh thu &lt; 20 triệu ⟺ \\(50000x+100000y&lt;20000000\\). Dấu \\(=\\) chỉ là hòa vốn, không phải bù lỗ.",
    },
    {
      level: 1,
      title: "Dạng tổng quát",
      prompt: "Trong các khẳng định sau, khẳng định nào đúng về <strong>bất phương trình bậc nhất hai ẩn</strong>?",
      options: [
        "Dạng \\(ax^2+by+c&lt;0\\) với \\(a\\ne0\\)",
        "Dạng \\(ax+by+c&lt;0\\) (hoặc \\(&gt;,\\le,\\ge\\)), trong đó \\(a,b\\) không đồng thời bằng 0",
        "Dạng \\(\\dfrac{a}{x}+by=0\\)",
        "Dạng \\(\\sin x+y&gt;0\\)",
      ],
      answer: 1,
      explain: "Bậc nhất hai ẩn: mỗi ẩn có bậc tối đa 1, không có tích \\(xy\\) hay hàm lượng giác; \\(a\\) và \\(b\\) không cùng bằng 0.",
    },
    {
      level: 1,
      title: "Nhận biết dạng",
      prompt: "Biểu thức nào sau đây là bất phương trình bậc nhất hai ẩn?",
      options: ["\\(2x-y+1&lt;0\\)", "\\(x^2+y&lt;1\\)", "\\(x+3=0\\)", "\\(xy-2&gt;0\\)"],
      answer: 0,
      explain: "A đúng dạng. B có \\(x^2\\) (bậc hai). C là phương trình một ẩn. D có tích \\(xy\\) nên không phải bậc nhất.",
    },
    {
      level: 2,
      title: "Nhận nghiệm",
      prompt: "Cho bất phương trình \\(x-2y+1&lt;0\\). Cặp số nào là một nghiệm của bất phương trình?",
      options: ["\\((0;1)\\)", "\\((0;0)\\)", "\\((3;0)\\)", "\\((2;-1)\\)"],
      answer: 0,
      explain: "Thay lần lượt: A: \\(0-2+1=-1&lt;0\\) đúng. B: \\(1&lt;0\\) sai. C: \\(4&lt;0\\) sai. D: \\(2+2+1=5&lt;0\\) sai.",
    },
    {
      level: 2,
      title: "Số nghiệm",
      prompt: "Về số nghiệm của một bất phương trình bậc nhất hai ẩn, khẳng định nào đúng?",
      options: [
        "Luôn có đúng một nghiệm \\((x_0;y_0)\\)",
        "Luôn có đúng hai nghiệm",
        "Luôn có vô số nghiệm (miền là nửa mặt phẳng)",
        "Có thể vô nghiệm nếu hệ số âm",
      ],
      answer: 2,
      explain: "Đường thẳng biên chia mặt phẳng thành hai nửa; một nửa (có hoặc không kể bờ) gồm vô số điểm thỏa BPT.",
    },
    {
      level: 2,
      title: "Loại nghiệm giả",
      prompt: "Cho \\(2x-y-3\\ge0\\). Cặp nào <strong>không</strong> là nghiệm?",
      options: ["\\((2;1)\\)", "\\((3;3)\\)", "\\((1;0)\\)", "\\((0;-4)\\)"],
      answer: 2,
      explain: "A: \\(4-1-3=0\\ge0\\) đúng (nằm trên bờ). B: \\(6-3-3=0\\ge0\\) đúng. C: \\(2-0-3=-1\\ge0\\) sai. D: \\(0+4-3=1\\ge0\\) đúng.",
    },
    {
      level: 3,
      title: "Miền nghiệm",
      image: asset("images/bai3/halfplane.jpg"),
      prompt: "Trên mặt phẳng tọa độ, miền nghiệm của bất phương trình bậc nhất hai ẩn là tập hợp nào?",
      options: [
        "Một điểm duy nhất",
        "Một đoạn thẳng hữu hạn",
        "Một nửa mặt phẳng (có kể hoặc không kể đường biên, tùy dấu)",
        "Toàn bộ mặt phẳng tọa độ",
      ],
      answer: 2,
      explain:
        "Bờ \\(ax+by+c=0\\) chia mặt phẳng thành hai nửa; miền nghiệm là đúng một nửa đó, có/không kể bờ tùy \\(\\le,\\ge\\) hay \\(&lt;,&gt;\\).",
    },
    {
      level: 3,
      title: "Các bước vẽ miền",
      prompt: "Khi biểu diễn miền nghiệm của \\(ax+by+c&lt;0\\) trên mặt phẳng, thứ tự thao tác nào đúng?",
      options: [
        "Tô màu trước, rồi mới vẽ đường thẳng biên",
        "Vẽ đường thẳng biên → chọn điểm thử (không trên biên) → thay vào BPT → tô nửa mặt phẳng thỏa",
        "Chỉ cần chọn điểm thử, không cần vẽ đường thẳng",
        "Vẽ hai đường thẳng vuông góc rồi tô hình chữ nhật",
      ],
      answer: 1,
      explain: "Quy trình chuẩn SGK: vẽ bờ, thử một điểm, kết luận nửa mặt phẳng, nhớ dấu nghiêm ngặt thì không tô bờ.",
    },
    {
      level: 3,
      title: "Điểm thử gốc",
      prompt:
        "Đang tìm miền nghiệm của một BPT bậc nhất hai ẩn. Biết điểm \\(O(0;0)\\) <strong>không nằm trên biên</strong> và khi thay vào thì bất phương trình <strong>đúng</strong>. Kết luận nào đúng?",
      options: [
        "Miền nghiệm không chứa gốc tọa độ",
        "Miền nghiệm chứa gốc tọa độ",
        "Miền nghiệm chỉ gồm đúng đường biên",
        "BPT vô nghiệm",
      ],
      answer: 1,
      explain: "Điểm thử thỏa ⇒ nửa mặt phẳng chứa điểm đó là miền nghiệm ⇒ miền chứa \\(O\\).",
    },
    {
      level: 4,
      title: "Thiếu vé loại 2",
      image: asset("images/bai3/cinema.jpg"),
      prompt:
        "Điều kiện không lỗ: \\(x+2y\\ge400\\) (đã rút gọn từ doanh thu ≥ 20 triệu; \\(x,y\\) lần lượt là số vé loại 1 và loại 2). Rạp đã bán được 80 vé loại 1. Hỏi cần bán <strong>ít nhất</strong> bao nhiêu vé loại 2 để không lỗ?",
      options: ["120", "140", "160", "200"],
      answer: 2,
      explain: "\\(80+2y\\ge400\\Rightarrow 2y\\ge320\\Rightarrow y\\ge160\\). Vậy tối thiểu 160 vé loại 2.",
    },
    {
      level: 4,
      title: "Đúng biên hòa vốn",
      prompt:
        "Với điều kiện không lỗ \\(x+2y\\ge400\\) (\\(x,y\\ge0\\)), cặp nào sau đây là trường hợp <strong>hòa vốn đúng biên</strong> (doanh thu đúng 20 triệu), còn các cặp còn lại thì hoặc lỗ hoặc lãi?",
      options: ["\\((100;100)\\)", "\\((200;100)\\)", "\\((50;180)\\)", "\\((0;190)\\)"],
      answer: 1,
      explain:
        "Biên: \\(x+2y=400\\). A: \\(100+200=300&lt;400\\) lỗ. B: \\(200+200=400\\) hòa vốn. C: \\(50+360=410&gt;400\\) lãi. D: \\(0+380=380&lt;400\\) lỗ.",
    },
    {
      level: 4,
      title: "Hai điều kiện",
      prompt:
        "Rạp cần không lỗ \\(x+2y\\ge400\\) và muốn bán vé loại 2 không quá một nửa số vé loại 1, tức \\(y\\le\\dfrac{x}{2}\\) (\\(x,y\\ge0\\)). Cặp nào thỏa <strong>đồng thời</strong> cả hai điều kiện?",
      options: ["\\((200;120)\\)", "\\((300;100)\\)", "\\((100;200)\\)", "\\((250;140)\\)"],
      answer: 1,
      explain:
        "A: \\(200+240=440\\ge400\\) nhưng \\(120\\le100\\)? Sai. B: \\(300+200=500\\ge400\\) và \\(100\\le150\\) đúng. C: \\(100+400=500\\ge400\\) nhưng \\(200\\le50\\)? Sai. D: \\(250+280=530\\ge400\\) nhưng \\(140\\le125\\)? Sai.",
    },
    {
      level: 4,
      title: "Đảo chiều khi nhân âm",
      prompt:
        "Bắt đầu từ \\(-2x+y-4&gt;0\\). Sau khi nhân cả hai vế với \\(-1\\) (nhớ đổi chiều bất đẳng thức), bất phương trình tương đương là gì?",
      options: ["\\(2x-y+4&gt;0\\)", "\\(2x-y+4&lt;0\\)", "\\(2x-y-4&lt;0\\)", "\\(-2x+y-4&lt;0\\)"],
      answer: 1,
      explain: "Nhân \\(-1\\): dấu &gt; đổi thành &lt;. Vế trái thành \\(2x-y+4\\). Được \\(2x-y+4&lt;0\\).",
    },
  ],
};
